### ISSUE TITLE
[Not an issue]: Very possibly impossible.

### ISSUE THREAD

**Issue by foxsouns** [kayos156/BoundFight#8]
This hurts. I love it. I wish the discussions tab was enabled here, so that I didn't have to clutter up an issue. Have a wonderful day, ty for makin this.

**Comment by kckarnige** [comment]
It's possible, it's just really, really, _reallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreally_ hard -w-

*(I'd say 95% success rate)*
